<%@ Page
  Language="C#"
  AutoEventWireup="true"
  CodeBehind="products.aspx.cs"
  UnobtrusiveValidationMode="None"
  Inherits="WebApp_SQL_Cookies.Web_products" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
  <title>Products</title>
  <link type="text/css" rel="stylesheet" href="products.css" />
</head>
<body>
  <%-- Nav --%>
  <div class="navBar">
    <ul class="navBar__ul">
      <%-- INDEX --%>
      <li class="navBar__ul__li">
        <asp:HyperLink ID="linkIndex"
          runat="server"
          NavigateUrl="~/index.aspx"
          CssClass="navBar__link ">
                    Home
        </asp:HyperLink>
      </li>
      <%-- PRODUCTS --%>
      <li class="navBar__ul__li">
        <asp:HyperLink ID="linkProducts"
          runat="server"
          NavigateUrl="~/products.aspx"
          CssClass="navBar__link active">
                    Productos 
        </asp:HyperLink>
      </li>
      <%-- EJERCICIO-2--%>
      <li class="navBar__ul__li">
        <asp:HyperLink ID="HyperLink1"
          runat="server" NavigateUrl="~/cookie.aspx"
          CssClass="navBar__link">
                    Cookie 
        </asp:HyperLink>
      </li>
    </ul>
  </div>

  <h1 class="title">Productos</h1>
  <form id="form1" runat="server">
    <div>
      <asp:GridView ID="gridProducts" runat="server"
        AutoGenerateColumns="False"
        PageSize="10" AllowPaging="True" OnPageIndexChanging="gridProducts_PageIndexChanging"
        AutoGenerateDeleteButton="True" OnRowDeleting="gridProducts_RowDeleting"
        AutoGenerateEditButton="True" OnRowEditing="gridProducts_RowEditing"
        OnRowCancelingEdit="gridProducts_RowCancelingEdit" OnRowUpdating="gridProducts_RowUpdating"
        CssClass="grid-view"
        EditRowStyle-CssClass="edit-row"
        RowStyle-CssClass="row-style"
        AlternatingRowStyle-CssClass="alternating-row"
        HeaderStyle-CssClass="header-style"
        PagerStyle-CssClass="pager-style"
        EditText="Update" DeleteText="Delete">

        <AlternatingRowStyle CssClass="alternating-row" />
        <%-- COLUMNAS --%>
        <Columns>
          <%-- ID PRODUCTO  --%>
          <asp:TemplateField HeaderText="Id Producto">
            <%-- ADD --%>
            <ItemTemplate>
              <asp:Label ID="itemTemplate_IDProducto" runat="server" Text='<%# Bind("IdProducto") %>'></asp:Label>
            </ItemTemplate>
            <%-- EDIT --%>
            <EditItemTemplate>
              <asp:Label ID="edit_itemTemplate_IDProducto" runat="server" Text='<%# Bind("IdProducto") %>'></asp:Label>
            </EditItemTemplate>
          </asp:TemplateField>

          <%-- NOMBRE DEL PRODUCTO --%>
          <asp:TemplateField HeaderText="Nombre del Producto">
            <%-- ADD --%>
            <ItemTemplate>
              <asp:Label ID="itemTemplate_NombreProducto" runat="server" Text='<%# Bind("NombreProducto") %>'></asp:Label>
            </ItemTemplate>
            <%-- EDIT --%>
            <EditItemTemplate>
              <asp:TextBox ID="edit_itemTemplate_NombreProducto" runat="server" Text='<%# Bind("NombreProducto") %>'></asp:TextBox>
            </EditItemTemplate>
          </asp:TemplateField>

          <%-- CANTIDAD POR UNIDAD --%>
          <asp:TemplateField HeaderText="Cantidad Por Unidad">
            <%-- ADD --%>
            <ItemTemplate>
              <asp:Label ID="itemTemplate_CantidadPorUnidad" runat="server" Text='<%# Bind("CantidadPorUnidad") %>'></asp:Label>
            </ItemTemplate>
            <%-- EDIT --%>
            <EditItemTemplate>
              <asp:TextBox ID="edit_itemTemplate_CantidadPorUnidad" runat="server" Text='<%# Bind("CantidadPorUnidad") %>'></asp:TextBox>
            </EditItemTemplate>
          </asp:TemplateField>

          <%-- PRECIO POR UNIDAD --%>
          <asp:TemplateField HeaderText="Precio Unidad">
            <ItemTemplate>
              <asp:Label ID="itemTemplate_PrecioUnidad" runat="server" Text='<%# Bind("PrecioUnidad") %>'></asp:Label>
            </ItemTemplate>
            <EditItemTemplate>
              <asp:TextBox ID="edit_itemTemplate_PrecioUnidad" runat="server" Text='<%# Bind("PrecioUnidad") %>'> </asp:TextBox>
            </EditItemTemplate>
          </asp:TemplateField>

        </Columns>
      </asp:GridView>
    </div>
    <hr />
    <%-- S.O MESSAGE --%>
    <span class="SO_message">
      <%-- TEST OF THE TIMER --%>
      <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
      <asp:Timer ID="timerCount" runat="server" Interval="3000" OnTick="timerCount_Tick"></asp:Timer>
      <asp:Label Text="" runat="server" ID="lblShow_SO"></asp:Label>
    </span>
  </form>
</body>
</html>
<%-- TODO: When a declated a variable , pls you're more much specific with the IDControl --%>